// src/components/Footer.jsx
import { AppBar, Container, Toolbar, Typography, Link } from '@mui/material';

const Footer = () => {
	return (
		<>
        <AppBar position="fixed" sx={{ top: 'auto', bottom: 0, bgcolor: "#000000cc", backdropFilter: "blur(10px)" }}>
          <Container maxWidth="sm" >
            <Toolbar sx={{ justifyContent: "center" }}>
              <Typography variant="body2">
								&copy; Copyrights 2021 by <Link href="https://drish-xd.is-a.dev" color="secondary" underline="hover" target="_blank" >Drish</Link>. All Rights Reserved.
              </Typography>
            </Toolbar>
          </Container>
        </AppBar>
		</>
	)
}

export default Footer;

// src/components/Footer.vue
<template>
    <div>
        <footer class="fixed w-full bottom-0 text-sm xl:text-base text-white bg-black bg-opacity-50 text-center px-2 py-4"> &copy; Copyrights 2021 by <a class="text-yellow-400 hover:underline" href="http://drish-xd.is-a.dev/">Drish</a>. All Rights Reserved.</footer>
    </div>
</template>
<script>
export default {
    
}
</script>
<style scoped>

</style>
